---
- name: first playbook
  hosts: myvm
  remote_user: vagrant
  vars_files:
   - vars/main.yml
  tasks:
   - name: create directory
     file:
       path: /tmp/{{ dir_name }}
       state: directory

   - name: create file inside directory
     file:
       path: /tmp/{{ dir_name }}/{{ file_name }}
       state: touch

      
