#=========================== Filebeat prospectors =============================
filebeat.prospectors:
    -
      paths:
        - /var/log/messages
        - /var/log/cron
        - /var/log/secure
        - /var/log/maillog
        - /var/log/firewalld
      input_type: log
      document_type: syslog
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/audit/audit.log
      input_type: log
      document_type: audit
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/redis/redis.log
      input_type: log
      document_type: redis
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/httpd/access_log
      input_type: log
      document_type: apache
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/httpd/*access.log
      input_type: log
      document_type: apache-other-vhost
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/httpd/*log
      input_type: log
      document_type: apache-error
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/yum.log
      input_type: log
      document_type: dpkg
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/www/DigitalException/log/pod*.log
      input_type: log
      document_type: syslog
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/www/DigitalException/log/derogation*.log
        - /var/www/DigitalException/log/bot*.log
      input_type: log
      document_type: shellbot
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/www/escalation/log/escalation*.log
      input_type: log
      document_type: bot
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/www/ServiceDeskBot/log/*.log
      input_type: log
      document_type: bot
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/www/SparkBotAdv/log/*.log
      input_type: log
      document_type: bot
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/www/SparkBotCmd/log/*.log
      input_type: log
      document_type: bot
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/www/TechRequest/log/*.log
      input_type: log
      document_type: syslog
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/VCS/*/*
      input_type: log
      document_type: vcs
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/infra/*/*
      input_type: log
      document_type: infra
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/cucm/sylog/*/*
      input_type: log
      document_type: cucm-syslog
      fields_under_root: true
      fields:
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/cucm/CLUSTERID-FR0/cdr*
      input_type: log
      document_type: cucm-cdr
      fields_under_root: true
      fields:
            cucm_clustername: CLUSTERID-FR0
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/cucm/CLUSTERID-FR0/cmr*
      input_type: log
      document_type: cucm-cmr
      fields_under_root: true
      fields:
            cucm_clustername: CLUSTERID-FR0
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/cucm/CLUSTERID-SP0/cdr*
      input_type: log
      document_type: cucm-cdr
      fields_under_root: true
      fields:
            cucm_clustername: CLUSTERID-SP0
            clientip: mypublicIPaddress

    -
      paths:
        - /var/log/cucm/CLUSTERID-SP0/cmr*
      input_type: log
      document_type: cucm-cmr
      fields_under_root: true
      fields:
            cucm_clustername: CLUSTERID-SP0
            clientip: mypublicIPaddress

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["localhost:5044"]
  ssl.enabled: false
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
  #ssl.certificate: "/etc/pki/tls/certs/logstash-forwarder.crt"
  #ssl.key: "/etc/pki/tls/private/logstash-forwarder.key"
#================================ Logging =====================================
logging.level: debug

