---
- name: installing the packages one by one
  hosts: my_vms
  become: true
  tasks:
   - name: Installing packages
     apt:
       name: git
       update_cache: yes
   - name: Installing nginx
     apt:
       name: nginx
       update_cache: yes
   - name: Installing memcached
     apt:
       name: memcached
       update_cache: yes
