# documentation: https://docs.ansible.com/ansible/devel/collections/ansible/builtin/sequence_lookup.html
---
  - name: Working with inventories
    hosts: vagrant
    gather_facts: false
    tasks:
      # show all the hosts in the inventory
      - debug: 
          msg: "{{ item }}"
        with_items:
          - "{{ groups['database'] }}"
        tags:
          - groups

      # show all the hosts in the current play
      - debug:
          msg: "{{ item }}"
        with_items:
          - "{{ ansible_play_batch }}"
        tags:
          - playbook_batch_only
      
      # show all the hosts in the inventory
      - debug:
          msg: "{{ item }}"
        with_inventory_hostnames:
          - all
        tags:
          - all_inventories
