---
- name: Nested Loop Test
  hosts: all
  tasks:
    - name: Nested Loop Test
      debug:
        msg: "Full name of the user {{ item[0] }} {{ item[1] }}"
      with_nested:
        - [ 'calvin', 'josh', 'alice' ]
        - [ 'jha', 'joshi', 'chaudhary' ]
